### ISSUE TITLE
something wrong in csv address index.

### ISSUE THREAD

**Issue by true-zk** [Learner0x5a/Callee-Dataset#1]
address in release.csv file can not match which in funcs files.

e.g. the first line in csv file, both 2 address can not find in corresponding files.

**Comment by Learner0x5a** [comment]
For wllvm-compiled targets, there is a base addr 0x400000. Please add this base addr.
E.g., 0x100019 + 0x400000 -> 0x500019

**Comment by true-zk** [comment]
prompt res~~
thanks a lot!
